---
title: "自律的なチーム開発を目指して 2015年度後期"
author: '@mediba-kitada'
date: "2016年4月8日"
output:
  slidy_presentation:
    footer: "Copyright (c) 2016, @mediba-kitada"
---

# アジェンダ

- 話すこと
- 話さないこと
- 自律したチーム
- 自律するためのツール
- まとめ
- 考察:自律したチームは、幸せか

# 話すこと

> - ツールの紹介,ハマりどころ
> - 私見
> - 技術的な話がメインです

# 話さないこと

> - ひと
> - 文化や属人的な話はしません
> - CLAMS(Culture、Lean、Automation、Measurement、Sharing)

# 自律したチーム

- 成すべきことを成す
  - 納期や契約を厳守する
  - 課題を必ず解決する
- よしなに成す
  - 課題をいい具合に解決する
  - メンバー各自の長所と役割がマッチしている

# 自律するためのツール - 選定 -

> - メンバーのスキルから自律しづらい分野を特定する
  - おすすめ開発では、構成管理が自律出来なさそうだった
- 自律しづらい分野は、省力化のためのツールを探す
  - 属人化しない(コードに落とせる)
  - テスト大事
> - ツールの導入は、リーダーが体を張る
  - 新しいツールの導入はしんどい
  - 自律したチームを夢見て頑張る
> - 本スライドは、環境構築にフォーカスします

# 自律するためのツール

- [OpsWorks](https://aws.amazon.com/jp/opsworks/)
- [Chef](https://www.chef.io/chef/)
- [Serverspec](http://serverspec.org/)
- [Test Kitchen](http://kitchen.ci/)
- [Packer](https://www.packer.io/)
- [Atlas](https://atlas.hashicorp.com)
- [Vagrant](https://www.vagrantup.com/)

# 自律するためのツール - OpsWorks -

- 商用環境へのプロビジョニング、デプロイを念頭に置く
  - OpsWorksの導入
  - 会員特典プロビジョニングで実績があった
- プロビジョニングしてみる
- デプロイしてみる

# 自律するためのツール - 構成管理 -

- OpsWorksを利用するので構成管理には、chefのレシピ(クックブック)が必要
  - OpsWorksのカスタムクックブックとして実装する
	- リポジトリのルートディレクトリにクックブックを配置
  - [CHEF Supermarket](https://supermarket.chef.io/)でクックブック開発の効率化を図る
- Serverspecでインフラテストを書く
- Test Kitchenでインフラテストを実行する

# 自律するためのツール - ローカル開発環境 -

- テスト済みのレシピをローカル開発環境のビルドに利用する
  - 全環境の構成管理を同一レシピで実現する
- ローカル開発環境のビルドをパックする
  - Packerを用いてVagrant boxファイルを生成する
- 構成管理のバージョンを管理する
  - Atlasを用いて構成管理のバージョンを可視化し、管理可能にする
- ローカル開発環境をビルドする
  - Atlasからバージョン管理されたboxをダウンロード
  - 開発メンバーは、vatrant upするだけ

# 自律するためのツール - 補足 -

- Q:なんでOpsWorksなの??
  - A:複数のアプリケーション(合計6)の構成管理の実現に必要だった
	- フロントエンド:2
    - バックエンド:1
    - 運用ツール:1
    - 攻撃ツール:1
	- スタブ:1
    - 3環境

# 自律するためのツール - 補足 -

- Q:複雑じゃない??
  - A:開発メンバーの負荷は減りました
    - VirtualBoxのバージョン、Vagrantのバージョン、ruby,chef等の職人化の要素を隠蔽しました

# まとめ

- アプリケーションエンジニアとして集中すべきことに集中出来る環境を整備しました
  - ローカル開発環境のビルドを省力化
  - プロビジョニングやデプロイを省力化
- アプリケーションエンジニアも構成管理出来るツールを整備しました
  - Infrastructure As Codeの実現
  - 構成管理のバージョン管理
- 自動化は継続的に取り組みます
  - TravisCIでTest Kitchen
  - AtlasでVagrant boxをビルド
  - OpsWorksでプロビジョニング

# 考察:自律したチームは、幸せか

- 自律したチームには発生条件があるように思う
  - 誰が上流か??どんな上流か??どこからが上流か??
  - 自律するための社会学的条件は別の機会に考察したい
- 開発メンバー曰く「楽しかった」
- サーバントリーダーシップ(奉仕のリーダー)は取れた
  - [良い兄貴](http://blog.yamotty.com/entry/20160118/1453068000)止まりになっていなかったか??
	- ビジョンは示せたか??
