---
title: "PHPアプリケーションに関する12の事実"
author: '@mediba-kitada'
date: "2016年11月3日"
output:
  slidy_presentation:
    incremental: true
    pandoc_args: [
      "--from", "markdown+autolink_bare_uris+tex_math_single_backslash-implicit_figures"
    ]
    footer: "Copyright (c) 2016, @mediba-kitada"
    css: ./assets/styles/slidy.css
---

```{r setup, include=FALSE}
# セットアップチャンク
library(knitr)
opts_knit$set(global.par = TRUE)
```

## 自己紹介

- エンジニアを募集しています

## はじめに

- とあるWEBサービスを他社から買収した
  - 契約やアカウント、コードベース含む事業の全てを譲り受けるプロジェクト

## タイムライン

- 上司がサーバサイドの開発リーダーを募集していたのが今年の5月中旬
- 事業譲渡完了予定日が6月1日
- 立候補し、コードベースの調査を開始したのが5月下旬
- 事業譲渡を無事に完了したのが6月1日
- チームを組んで移管に本格着手したのが7月初旬
- 複数回の商用リリースを実施したのが7,8,9,10月
- 計画していた全てのリリースを完了したのが、11月1日

## ミッションと開発指針

### ミッション

- ビジネスの停止に直結する単一障害点を除去する(可用性の向上)
- 自分たちのモノにする(移管する)

### 開発指針

- CMSアプリケーションをコンテナ化する
- 収益に貢献するため、運用コストを削減する
- 上記の実現の過程で、Twelve-Factor Appにする

## いくつかの真実

- 移管プロジェクトを通して実践したこと、気づいたことをお話します
  - 明日から現場で取り組めるようにコードを例にお話します

## 話さないこと

- 単一障害点の除去
- チーム開発のあれこれ
- WEBアプリケーションの性能

## 話すこと

- Twelve-Factor Appを実現するために用いたいくつかのプロダクトと気付き
    - factor:要素
    - fact:真実
    - 12の要素全てではない...!

## いくつかのプロダクト

- Docker
- Amazon EC2 Container Service
- Entrykit
- TravisCI

## Twelve-Factor App
## 設定
## 開発/本番一致
## ログ
## ビルド、リリース、実行
## サンプルアプリケーションの紹介

## 終わりに

- アプリケーションをサービス化したらやりたいことは?
	- 機能追加？
	- リファクタリング？
	- テストコード？
	- 更なる自動化？ 
- やりたいこと、やるべきことは限りなく湧き出てくる。優先順位を付けることが難しい面もある
	- その際、重要となるのはチームで課題に取り組める環境とアプリケーションがあり、良心のあるエンジニアがいること
	- 環境とアプリケーションは構築出来た
	- 良心のあるエンジニアになるのは、難しいがその過程は、とてもエキサイティング
- medibaでは、エキサイティングな経験を通して、一緒に成長出来るエンジニアを募集してます!
